### PR TITLE
Allow writing PLY-pointcloud files.

### LINKED ISSUE #904: PLY requires cells and thus cannot be used for pointclouds
I am trying to convert a `.obj` file to `.ply`. My `.obj` file is a point cloud, i.e. it contains only vertices, no faces and hence no normals. When trying to do so using `meshio` I get a `KeyError: None`.

I am not sure whether I am outside of `.ply` specification and this use case is actually not supported by `.ply`, or if this is a shortcoming of `meshio`'s  implementation. In any case I will create a PR shortly containing a fix for that. Any feedback is very much welcome.

### PR DESCRIPTION
**Pull request by sopherrmann**
Fixes #904.

### CODE REVIEW

**Comment by nschloe** [comment]
Run `make format` to make the linter happy.

**Comment by nschloe** [comment]
In which line does the error originally occur?

**Comment by sopherrmann** [comment]
I got the following stacktrace:
```
$ meshio-convert path/to/sample.obj path/to/sample.ply 
<meshio mesh object>
  Number of points: 4986
  No cells.
Traceback (most recent call last):
  File "/home/sophie/.virtualenvs/votenet/bin/meshio-convert", line 8, in <module>
    sys.exit(convert())
  File "/home/sophie/.virtualenvs/votenet/lib/python3.6/site-packages/meshio/_cli.py", line 50, in convert
    write(args.outfile, mesh, file_format=args.output_format)
  File "/home/sophie/.virtualenvs/votenet/lib/python3.6/site-packages/meshio/_helpers.py", line 133, in write
    return writer(filename, mesh, **kwargs)
  File "/home/sophie/.virtualenvs/votenet/lib/python3.6/site-packages/meshio/ply/_ply.py", line 408, in <lambda>
    "ply": lambda f, m, **kwargs: write(f, m, **kwargs, binary=True),
  File "/home/sophie/.virtualenvs/votenet/lib/python3.6/site-packages/meshio/ply/_ply.py", line 350, in write
    ply_type = numpy_to_ply_dtype[cell_dtype]
KeyError: None
```

**Comment by nschloe** [comment]
But line 350 looks different, right?

**Comment by nschloe** [comment]
Are you using an old version or so?

**Comment by sopherrmann** [comment]
Yes, you are right! I was testing using `meshio` 3.3.1. I upgraded to current version 4.1.1 and it works just fine.

Thanks for the help and sorry for the inconvenience!

**Comment by nschloe** [comment]
No problem.

**Pull request closed without merging**
