### PR TITLE
Add back setup.py for editable installations

### LINKED ISSUE #1223: Add developer install instructions
```
pip install -e .
``` 
does not work on Python 3.8:

```
>>> import scooby
>>> scooby.Report(['setuptools', 'distutils'])

--------------------------------------------------------------------------------
  Date: Mon Nov 29 11:40:24 2021 MST

                OS : Darwin
            CPU(s) : 16
           Machine : x86_64
      Architecture : 64bit
       Environment : Python

  Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:12:38)
  [Clang 11.0.1 ]

        setuptools : 49.6.0.post20210108
         distutils : 3.8.8
             numpy : 1.20.2
             scipy : 1.6.3
           IPython : 7.22.0
        matplotlib : 3.4.1
            scooby : 0.5.7
--------------------------------------------------------------------------------
```

It appears the setup.py was removed (without warning?) in https://github.com/nschloe/meshio/pull/795

Since the typical way of installing isn't working, there should be an explanation of the usage of `setup.cfg` in the README and how to install this locally

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #1223

### CODE REVIEW

**Comment by nschloe** [comment]
I was pretty happy to finally be able to _remove_ `setup.py` when I did. Nevertheless, I am willing to merge this _if_ there's a perspective of removing it again. What's the future replacment idea for `pip install -e` in absence of `setup.py`?

**Comment by banesullivan** [comment]
> What's the future replacment idea for pip install -e in absence of setup.py?

Honestly, I have no idea. All this `setup.cfg` stuff is very new to me. I think `meshio` should have the `setup.py` until there is a clear cut way to do this (googling gave no hints)

**Comment by nschloe** [comment]
I'd say you best add your `setup.py` locally, and I'll keep an eye out for how this is supposed to go in a `setup.cfg` or -- even more modern -- `pyproject.toml` workflow.

**Comment by nschloe** [comment]
Here's the corresponding setuptools documentation. https://github.com/pypa/setuptools/issues/2816

**Comment by akaszynski** [comment]
You can have an editable install with:
```
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
```

I'd prefer using `setuptools`, but it looks like `filt` works.

**Comment by GenevieveBuckley** [comment]
I realise this is an older PR, but it's probably unnecessary now. Pip has had support for `pyrpoject.toml` editable installations since [pip version 21.3 (2021-10-11)](https://pip.pypa.io/en/stable/news/#v21-3):

> Support editable installs for projects that have a pyproject.toml and use a build backend that supports [PEP 660](https://peps.python.org/pep-0660/). ([#8212](https://github.com/pypa/pip/issues/8212))

**Comment by banesullivan** [comment]
Thanks for the follow up @GenevieveBuckley! Indeed this is unnecessary as of now.

I finally bit the bullet and familiarized with pyproject.toml since this was opened

**Pull request closed without merging**
