### PR TITLE
Gmsh: Various fixes and refactor

### PR DESCRIPTION
**Pull request by dalcinl**
* Fix read/write for periodic section.
* Fix bad data types for v4.0 reader.
* Platform independent (32/64 bits) v4.1 reader.
* Get rid of ctypes data types in favor of NumPy.

### CODE REVIEW

**Comment by dalcinl** [comment]
@nschloe It was not fun, many small issues here and there. I confirm the readers work for v2.2, v4.0, and v4.1 both ASCII and binary (for meshed generated in Linux 64 bits).

I do have a set of of very small meshes with periodic section, in all formats and binary 32/64 within the [PETSc repository](https://github.com/petsc/petsc/tree/master/share/petsc/datafiles/meshes), look for `gmsh-3d-{ascii|binary}-[{32|64}].msh[24]`. However, I have no clue how your `gh-pages` trick works.

Eventually, It would be nice to add a proper writer for v4.1, but the handling Gmsh entities requires some refactor (e.g. add a `gmsh_entity` attr to `Mesh`), plus figuring out how to synthesize the entity section from alien formats.

**Comment by dalcinl** [comment]
@nschloe The version map `{..., "4": msh4_1}` is OK for the writer. However, IMHO, for the reader it should be `{..., "4": msh4_0}`. Suppose you download a legacy Gmsh app version that dumps the outdated v4.0, it writes a plain `4` in the header, so if you try to read, boom! Would you agree to such a fix? 

Or maybe, given than v4.0 is outdated, and it was superseded by v4.1 within a few months (half a year), we should just kill the v4.0 reader/writter for good and move forward. Who is going to waste its time to implement a writer for the defunct v4.0?

**Comment by nschloe** [comment]
> The version map {..., "4": msh4_1} is OK for the writer. However, IMHO, for the reader it should be {..., "4": msh4_0}. Suppose you download a legacy Gmsh app version that dumps the outdated v4.0, it writes a plain 4 in the header, so if you try to read, boom! Would you agree to such a fix?

I'm not sure right now: Does Gmsh 4.2 (with it's output format 4.1, _sheesh_) also put a plain 4 in the header?

> Or maybe, given than v4.0 is outdated, and it was superseded by v4.1 within a few months (half a year), we should just kill the v4.0 reader/writter for good and move forward. Who is going to waste its time to implement a writer for the defunct v4.0?

One big problem is that gmsh 4.1 is in Ubuntu, and people will use it for a while and produce meshes with it, even if it's outdated. And those meshes will be around forever, so we'll have to have a _reader_ for it. We can perhaps ditch the writer in the the future, but since we have a reader anyways, it doesn't hurt too much.

**Comment by nschloe** [comment]
The gh-pages thing isn't a trick really: It's just a file storage that can be used to fetch meshes from. The tests (in master) then just download them from there, try to read them, and assert some checksums on the point data (or whatever you want). It was @gdmcbain's idea and I like it a lot since now for the first time we're actually testing that the reader does the right thing. Could be handy in the case of gmsh especially.

**Comment by nschloe** [comment]
Btw the `square_bin.msh` in https://github.com/petsc/petsc/tree/master/share/petsc/datafiles/meshes has 755 permissions.

**Comment by gdmcbain** [comment]
> It was @gdmcbain's idea 

Actually I was meaning to ask for the rationale behind storing the authoritative examples in a nonmaster branch and then having the tests download them from the WWW each time the test is run. My idea was simply having a set of genuinely generated meshes; I hadn't specified where to store them. I had been imagining keeping them in the master branch but in a directory that would not be installed by a regular pip-install, i. e. only by those git-cloning, presumably developers. I assume the test directory is like this? I'm not really worried about this but was curious.

**Comment by dalcinl** [comment]
> Does Gmsh 4.2 (with it's output format 4.1) also put a plain 4 in the header?

This is the last version released to produce outdated format v4.0 (writes **4** in header):
```
$ gmsh-4.1 --version
4.1.5
$ gmsh-4.1 -v 0 -3 tmp.geo && head -n 3 tmp.msh 
$MeshFormat
4 0 8
$EndMeshFormat
```

This is the LATEST version, which produces format v4.1 (writes **4.1** in header):
```
$ gmsh-4.2 --version
4.2.2
$ gmsh-4.2 -v 0 -3 tmp.geo && head -n 3 tmp.msh 
$MeshFormat
4.1 0 8
$EndMeshFormat
[dalcinl@kw60439 tmp]$ 
```

So, you see, we really need to map `{"4" : mesh4_0}` for the reader. So you mentioned Ubuntu providing gmsh-4.1, assuming this version writes "4" in the header (didn't check, I do not use Ubuntu, maybe they patched gmsh to write "4.0"?),  then `meshio` will try to read as format v4.1, and fail.

**Comment by dalcinl** [comment]
> Btw the `square_bin.msh` in https://github.com/petsc/petsc/tree/master/share/petsc/datafiles/meshes has 755 permissions.

Noted, thanks. Pull-request submitted in Bitbucket.

**Comment by dalcinl** [comment]
> > It was @gdmcbain's idea
> 
> Actually I was meaning to ask for the rationale behind storing the authoritative examples in a nonmaster branch and then having the tests download them from the WWW each time the test is run.

Oh, I see now. It makes simply no sense! These tests meshes should just be there in master under let say `test\meshes\msh`.

**Comment by gdmcbain** [comment]
> Eventually, It would be nice to add a proper writer for v4.1, but the handling Gmsh entities requires some refactor (e.g. add a `gmsh_entity` attr to `Mesh`)

While I did myself stumble at the hurdle of entities on trying to write MSH4.1 #332, I do hope that it will be possible to avoid introducing another format-specific attribute into `meshio.Mesh`.

**Comment by dalcinl** [comment]
@nschloe OK, at this time I gently request move forward. Either explicitly accept my proposal for mapping 4->4.0 on read, and then I'll update this PR, or reject it [and live with the consequences :smiley:] and merge this PR as is.

**Comment by gdmcbain** [comment]
> mapping 4->4.0 on read

I had prepared a PR for this on Friday while working on #358. I didn't end up pushing it as the OP was able to wipe the defective Gmsh 4.1, upgrade to Gmsh 4.2, and regenerate the mesh as MSH4.1. This is the preferred solution, but unhappily it does seem that Gmsh 4.1 has some currency; that's really unfortunate news that Ubuntu are shipping it. I don't use that distro much myself but it's the basis for many containers and cloud images.

**Comment by dalcinl** [comment]
@gdmcbain Anyway, the 4.1 reader had some minor issues here and there. The fixes in this PR should resolve them all, hopefully.

**Comment by dalcinl** [comment]
> > mapping 4->4.0 on read
> 
> I had prepared a PR for this on Friday while working on #358.

@gdmcbain So do do you agree that mapping 4->4.0 on read is the right thing to do?

**Comment by nschloe** [comment]
> So do do you agree that mapping 4->4.0 on read is the right thing to do?

I think we all agree here, [this](https://github.com/nschloe/meshio/pull/365#issuecomment-475858119) is very good evidence. If you could update the PR, I'll merge right away.

> Oh, I see now. It makes simply no sense! These tests meshes should just be there in master under let say test\meshes\msh.

The idea of not storing meshes in the master branch comes from bad experiences I've have with Trilinos. There, all test data is stored in master, and the meshes used there are _huge_. Not only does everyone who ever uses Trilinos have to download the meshes, even if having no intention of running the tests. What's worse is that the meshes are forever engraved in git history, so pulls are terribly slow even if the meshes are removed now.
Lesson from that: No heavy data in code branches. (The same applied to images etc.)

I do realize that this is a bit inconvenient, e.g., in having to file two separate PRs for master and gh-branches. Also, _so far_, our meshes are relatively small. I might change my mind in the future about this, but let's be conservative for now.

**Comment by dalcinl** [comment]
@nschloe OK, two commits for unrecognized sections, do not merge just yet. I'm starting to work in the 4->4.0 mapping on read.

**Comment by nschloe** [comment]
> do not merge just yet. 

Best say `[WIP]` in the title.

**Comment by dalcinl** [comment]
@nschloe Ready to go from my side. I've tested the reader for the cross product {2.2,4.0.,.1}x{ascii,binary} plus some exported meshes (from a commercial mesh) generator having `$Comments` sections everywhere (even at the very beginning).

**Comment by nschloe** [comment]
Thanks for a great PR, @dalcinl!

**Pull request merged**
