### PR TITLE
Fix type in vtu_io

### PR DESCRIPTION
**Pull request by jdumas**
Getting the following error otherwise:
```
IndexError: arrays used as indices must be of integer (or boolean) type
```

### CODE REVIEW

**Comment by nschloe** [comment]
That's weird. How does the error occur? Can you post a mesh?

**Comment by jdumas** [comment]
Sure, here is it:
[job_0.vtu.zip](https://github.com/nschloe/meshio/files/3268626/job_0.vtu.zip)

**Comment by nschloe** [comment]
Closing in favor of #397. (It's better to set the dtype on the arange straight away.) Got to say I love this kind of PRs though: They fix the little thing that normally get overlooked ot make meshio a little better every time. Thanks!

**Comment by jdumas** [comment]
No worries, and thanks for making this lib! =)

**Pull request closed without merging**
