### PR TITLE
Fixed tecplot file key reading if 1st data is neg number

### PR DESCRIPTION
**Pull request by davidcortesortuno**
Converting a `.tec` file to any other format was failing for me if the first line of numerical data starts with a negative number, because the `isdigit` method was working only assuming the first character is `0-9` and not considering the `'-'` symbol. This caused numeric keys to be added as a zone entry. The fix is quite straightforward.

### CODE REVIEW

**Comment by nschloe** [comment]
I can only consider this if the tests are passing. Let me know if you're still working on this.

**Comment by davidcortesortuno** [comment]
Ok, I'll check the test errors and fix any problems

**Comment by nschloe** [comment]
Something seems to have gone wrong with the commits here.

**Comment by davidcortesortuno** [comment]
Yes, sorry, I just tried to merge with the changes of the main repo. Should I create a new pull request? The fix is very short

**Comment by nschloe** [comment]
Yeah, make a new PR.

**Pull request closed without merging**
