### PR TITLE
Add UNV mesh type support

### PR DESCRIPTION
**Pull request by EigenEmara**
Ideas-UNV mesh file read and write support for meshio.

### CODE REVIEW

**Comment by EigenEmara** [comment]
I tested `test_unv.py` locally and everything is okay. but I see the checks fail here because meshio has no unv module yet.

How do I fix this? (P.S. I am new to contributing 😅)

**Comment by keurfonluu** [comment]
> I tested `test_unv.py` locally and everything is okay. but I see the checks fail here because meshio has no unv module yet.
> 
> How do I fix this? (P.S. I am new to contributing 😅)

Use the function `register_format` to register your new format (obviously), and import `unv` in `meshio.__init__.py` to actually register the format.

**Comment by EigenEmara** [comment]
> > I tested `test_unv.py` locally and everything is okay. but I see the checks fail here because meshio has no unv module yet.
> > How do I fix this? (P.S. I am new to contributing 😅)
> 
> Use the function `register_format` to register your new format (obviously), and import `unv` in `meshio.__init__.py` to actually register the format.

Yes, of course!
thanks alot.

**Comment by nschloe** [comment]
Thanks @EigenEmara for the PR! Now, one thing I immediately notice is

screenshot

140k+ lines of code is a bit much! :smile: That's because you included your reference files raw in the repo. We don't do that in meshio, but rather first mark files for Git-LFS in `.gitattributes`, and then commit them. Could you please do that, too? That'll require a force-push to remove those huge files from history.

**Comment by EigenEmara** [comment]
> Thanks @EigenEmara for the PR! Now, one thing I immediately notice is
> 
> screenshot
> 
> 140k+ lines of code is a bit much! 😄 That's because you included your reference files raw in the repo. We don't do that in meshio, but rather first mark files for Git-LFS in `.gitattributes`, and then commit them. Could you please do that, too? That'll require a force-push to remove those huge files from history.

I added `*.unv filter=lfs diff=lfs merge=lfs -text` to `.gitattribute`, is that enough?

**Comment by nschloe** [comment]
> I added *.unv filter=lfs diff=lfs merge=lfs -text to .gitattribute, is that enough?

No, you need to add this _before_ commiting the unv files. You'll need to change history and force push, or start fresh.

**Comment by EigenEmara** [comment]
> No, you need to add this _before_ commiting the unv files. You'll need to change history and force push, or start fresh.
Sorry about the commit mess!
I prefer to start fresh, since I am not very experienced with git. Do I simply close the PR and start over with a new one?

**Comment by nschloe** [comment]
> Do I simply close the PR and start over with a new one?

Yes, with a new branch, new history etc.

**Pull request closed without merging**
