### PR TITLE
Fixed undefined variable gmsh_io

### PR DESCRIPTION
**Pull request by cbcoutinho**

### CODE REVIEW

**Comment by nschloe** [comment]
`points` is an array, so `points = []` would be more appropriate.

**Comment by cbcoutinho** [comment]
Good point - done

**Comment by nschloe** [comment]
Not sure why circleci won't build. Let me check back with their support.

**Comment by nschloe** [comment]
Aha, CircliCI's workflows (which meshio uses) doesn't support forked PRs yet, https://circleci.com/docs/2.0/faq/#can-i-build-fork-prs-using-workflows. I could swear that it briefly worked a while ago, but this might have been a fluke. Will fix this in master.

**Pull request merged**
