### PR TITLE
Fix issue #509

### PR DESCRIPTION
**Pull request by keurfonluu**
- Fixed: handle non-natural order point IDs.

### CODE REVIEW

**Comment by nschloe** [comment]
`point_ids` should be _returned_ from `read_points`.

**Comment by keurfonluu** [comment]
> `point_ids` should be _returned_ from `read_points`.

It's not possible. FLAC3D format has no separate point and cell sections (``* GRIDPOINTS`` and ``* ZONES`` are dummy comments). You are totally allowed to define a set of points, then a zone element, followed by another set of points, e.g.

```
G 1   2.10000000000000e+00   0.00000000000000e+00   3.10000000000000e+00
G 2   2.30564263324093e+00   0.00000000000000e+00   3.24739811913093e+00
G 3   2.10000000000000e+00   3.57711954132911e-01   3.10000000000000e+00
G 4   1.79145372108365e+00   0.00000000000000e+00   3.32724180720029e+00
G 5   2.30564263324093e+00   3.57711954132911e-01   3.24739811913093e+00
G 6   1.79145372108365e+00   3.57711954132911e-01   3.32724180720029e+00
G 7   1.96230278624208e+00   0.00000000000000e+00   3.47179049928151e+00
G 8   1.96230278624208e+00   3.57711954132911e-01   3.47179049928151e+00
Z B8 1 1 2 3 4 5 6 7 8
G 9   2.54644975339359e+00   0.00000000000000e+00   3.42000102750863e+00
G 10   2.54644975339359e+00   3.57711954132911e-01   3.42000102750863e+00
G 11   2.16236670641845e+00   0.00000000000000e+00   3.64105673417323e+00
G 12   2.16236670641845e+00   3.57711954132911e-01   3.64105673417323e+00
```

is a valid FLAC3D mesh file.

**Comment by nschloe** [comment]
I see. I still don't like how the `point_ids` dict is manipulated "behind the scenes". I'd like it better if `read_points` returned something, and that something is then incorporated into `point_ids` explicitly in `read`.

**Comment by nschloe** [comment]
Also, does it have to be a `dict`? A list of arrays (which are concatenated at the end) would be more efficient I guess. Not a must though.

**Comment by keurfonluu** [comment]
> I see. I still don't like how the `point_ids` dict is manipulated "behind the scenes". I'd like it better if `read_points` returned something, and that something is then incorporated into `point_ids` explicitly in `read`.

Got you.

> Also, does it have to be a `dict`? A list of arrays (which are concatenated at the end) would be more efficient I guess. Not a must though.

It might be more complicated to implement, I guess. The problem is that the format does not provide any indication about the total number of points (or cells)...

**Comment by nschloe** [comment]
Thanks!

**Pull request merged**
