### PR TITLE
Fix issue #831

### PR DESCRIPTION
**Pull request by keurfonluu**
- Fixed: convert cell data type to `int32` in VTK binary reader (fix issue #831).

### CODE REVIEW

**Comment by nschloe** [comment]
This does a copy, we'd rather avoid it. Why the change?

**Comment by keurfonluu** [comment]
`meshio`'s VTK format is forcing big endianness: https://github.com/nschloe/meshio/blob/ad906b4c2aa64635adfb3c076a0370ac8a4ff1ed/meshio/vtk/_vtk.py#L364).

The writer is storing data in big endian order:
https://github.com/nschloe/meshio/blob/ad906b4c2aa64635adfb3c076a0370ac8a4ff1ed/meshio/vtk/_vtk.py#L668

The reader is reading in big endian order:
https://github.com/nschloe/meshio/blob/ad906b4c2aa64635adfb3c076a0370ac8a4ff1ed/meshio/vtk/_vtk.py#L393

This causes cell connectivity data type to be `dtype('>i4')` which key does not exist in `numpy_to_vtu_type`

https://github.com/nschloe/meshio/blob/ad906b4c2aa64635adfb3c076a0370ac8a4ff1ed/meshio/vtu/_vtu.py#L230

thus raising the `KeyError: dtype('>i4')` observed in issue #831.

**Comment by nschloe** [comment]
Seems like we'd rather want to adapt the dictionary.

**Comment by nschloe** [comment]
I see
```python
# Use the native endianness. Not strictly necessary, but this simplifies things
# a bit.
```
We might want to change that to the endianness of the input data.

**Comment by keurfonluu** [comment]
After further investigations, I found it weird that `meshio.Mesh.points` with data type `dtype('>f8')` was successfully converted. It appears that the byte order of the attributes of a `meshio.Mesh` were all swapped except for `cells` in VTU writer.

**Comment by nschloe** [comment]
Not sure if we should do that at all. How about using the byteorder of the data, not system byte order? (as mentioned above)

**Comment by keurfonluu** [comment]
I tried using the data byteorder before coming up with the latter workaround. Didn't manage to produce a valid VTU file.

What I did:
1. Define byteorder from data if not native, otherwise from system,

```python
byte_order = mesh.points.dtype.byteorder
byte_order = (
    "LittleEndian" if sys.byteorder == "little" else "BigEndian"
    if byte_order == "="
    else "LittleEndian" if byte_order == "<" else "BigEndian"
)
```

2. Remove codes related to byte swapping,

3. Appended new keys to `numpy_to_vtu_type`:

```python
numpy_to_vtu_type[numpy.dtype(">i4")] = "Int32"
numpy_to_vtu_type[numpy.dtype(">f8")] = "Float64"
```

With these few modifications, ParaView fails to read the points (and probably the rest).

**Comment by nschloe** [comment]
`sys.byteorder` should now appear, only the data byte order.

**Comment by keurfonluu** [comment]
`dtype.byteorder` returns `"="` (native) for all arrays created by `numpy` unless explicitly stated in `dtype`.

**Comment by keurfonluu** [comment]
Another problem raised by determining byteorder from data is that since byteorder is a global attribute for VTU format, we have to assume that all the data in a mesh has the same byteorder if we want to avoid any conversion, which might not always be the case.

**Comment by nschloe** [comment]
Alright, let's do it like you suggest.

**Pull request merged**
