### PR TITLE
Gmsh: Support for writing optional PhysicalNames section

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by nschloe** [comment]
This still needs a test in `test/test_gmsh.py`. Now that I look at this, I see that `field_data` isn't tested very well at all. Let's add this. We should probably do something like:

   1. Add a `add_field_data()` method in `test/helpers.py` (just like the `add_point_data` and `add_cell_data` methods there).
   2. Add a test in `test/test_gmsh.py` where any mesh is equipped with the field data.
   3. Assert in `test/helpers.py::write_read` that input field data and output field data are the same.

**Comment by nschloe** [comment]
Best ping me once you've done this (I'm not getting notification for PR pushes.)

**Comment by dalcinl** [comment]
@nschloe PR updated. Do you want me to extend testing with bad field data to trigger the `logging.warning()` path and improve coverage?

**Comment by nschloe** [comment]
Thanks for the fixes! We can increase the coverage later.

**Pull request merged**
