### PR TITLE
Add addtional element types, include cell_data and field_data

### PR DESCRIPTION
**Pull request by cbcoutinho**
Howdy @nschloe,

I also needed some access to physical groups, so here's an update I made to return the physical group information if available. Otherwise, it just returns empty dictionaries as before. Feel free to hold off on merging for a bit, I'm still messing around with it.

I'm not sure what point_data is supposed to be, is that related to another mesh format?

Cheers,
Chris

### CODE REVIEW

**Comment by nschloe** [comment]
`point_data` is the data in mesh vertices (or wherever your DOFs are). I guess that's a common thing across most mesh formats.

**Comment by nschloe** [comment]
Many people requested the Gmsh physical group feature; see, e.g., https://github.com/nschloe/meshio/issues/43. Extra points if we get those use cases covered. (I'll help out where necessary.)

**Comment by cbcoutinho** [comment]
Oh alright, I didn't don't have point data so I just left it empty. 

I'm not at my computer to test their 3d example, but at a quick glance I think it should work. 

One downside in the way I implemented physical groups is omitting the dimension. I personally didn't need it, but if that's an issue for others we can try to come up with a better solution.

**Comment by cbcoutinho** [comment]
Another drawback - if an element is part of multiple groups, there's going to be a problem.

**Comment by nschloe** [comment]
Well, something is better than nothing. It'd be great if we could include a test for this such that I can remember in the future what meshio can an can't do.

**Comment by cbcoutinho** [comment]
Do you have a test format? I could write one, but I have no idea how Travis
works.

Chris

**Pull request merged**
