### PR TITLE
[WIP] Abaqus node and cell set

### PR DESCRIPTION
**Pull request by dbeurle**
Related #493.

### CODE REVIEW

**Comment by tianyikillua** [comment]
Maybe you know already, you can use `point_gids` to convert Abaqus node id's to the natural 0-based ordering index of `points`. The `point_sets` returned should not refer to the Abaqus node id's.

Similarly, a dictionary could be introduced for converting Abaqus cell id's to the index of `cells`.

**Comment by dbeurle** [comment]
> Maybe you know already, you can use `point_gids` to convert Abaqus node id's to the natural 0-based ordering index of `points`. The `point_sets` returned should not refer to the Abaqus node id's.
> 
> Similarly, a dictionary could be introduced for converting Abaqus cell id's to the index of `cells`.

Don't worry I'm getting there ;)

**Comment by nschloe** [comment]
> Don't worry I'm getting there ;)

Let's go @dbeurle! :smile_cat:

**Comment by dbeurle** [comment]
> > Don't worry I'm getting there ;)
> 
> Let's go @dbeurle! smile_cat

Sorry - I've been busy preparing for my defence in two weeks.  I can make time if I'm blocking someone else though.

**Comment by nschloe** [comment]
I just wanted to ping because as the more time passes, the more changes are happening in meshio and the higher the chances are for a difficult merge.

**Comment by dbeurle** [comment]
No problem, I can rebase.  There'll be some time before Christmas to get this locked away.  I appreciate the cat emojis, keep them coming!

**Comment by nschloe** [comment]
Considering the changes that meshio has undergone in the past months, it's probably smarter to restart this PR from a fresh checkout.

**Pull request closed without merging**
