### PR TITLE
skip COLOR_SCALARS gracefully in vtk files

### LINKED ISSUE #854: meshio._exceptions.ReadError: Unknown section 'COLOR_SCALARS'
```
import meshio
m = meshio.Mesh.read('test.vtk', "vtk")
m.write('test.dato')
```
[test.vtk.gz](https://github.com/nschloe/meshio/files/4823444/test.vtk.gz)

### PR DESCRIPTION
**Pull request by ChristosT**
This resolves #854 but the file attached to that issue cannot be read completly yet since it depends at least on #855 too.

### CODE REVIEW

**Comment by nschloe** [comment]
> cannot be read completly yet since it depends at least on #855 too.

Why do the tests pass then?

**Comment by ChristosT** [comment]
> > cannot be read completly yet since it depends at least on #855 too.
> 
> Why do the tests pass then?

I used a simpler file that just adds COLOR_SCALARS.

I will be looking to #855 soon so, as an alternative we can leave this open until I have both.

**Comment by nschloe** [comment]
> I used a simpler file that just adds COLOR_SCALARS.


I was just wondering if we shouldn't assert the existence and shape etc. of COLOR_SCALARS in the output.

**Comment by ChristosT** [comment]
> I was just wondering if we shouldn't assert the existence and shape etc. of COLOR_SCALARS in the output.

Sorry I didn't get that. With this commit the COLOR_SCALARS are skipped just like the LOOKUP_TABLE data. Are you suggesting that we should assert the existence and the size of the entry in the test ?

**Comment by ChristosT** [comment]
Together with #885 it can parse the test file in #854 successfully

**Comment by nschloe** [comment]
> With this commit the COLOR_SCALARS are skipped just like the LOOKUP_TABLE data.

Fair enough. This is already an improvement.

**Pull request merged**
