### PR TITLE
Fix a problem with element sets

### PR DESCRIPTION
**Pull request by nilswagner**

### CODE REVIEW

**Comment by nschloe** [comment]
I can merge when the linter is happy. `make lint`

**Comment by nschloe** [comment]
Why do you try-catch and then raise, just to print the set_ids from the previous step?

**Comment by nilswagner** [comment]
[tutorial.inp.txt](https://github.com/nschloe/meshio/files/3767635/tutorial.inp.txt)
mv tutorial.inp.txt tutorial.inp
meshio_convert tutorial.inp tutorial.dato
ValueError: invalid literal ...

**Comment by nschloe** [comment]
I understand, but you'll get the same error message with the patch, don't you? After all, you `raise`  the exception again.

**Comment by nilswagner** [comment]
My patch resolves the problem.
[tutorial.txt](https://github.com/nschloe/meshio/files/3767665/tutorial.txt)

**Comment by nschloe** [comment]
Okay, then it's the
```
        if not line:
            break
```
part that does the trick. If the try-catch block is a debugging relic (and it looks like one), please remove it.

**Pull request merged**
