### PR TITLE
MSH2.2 and MSH4.1 test meshes

### PR DESCRIPTION
**Pull request by gdmcbain**
Here's a couple of contributions to the test suite #335, generated by Gmsh 4.2.2-git-0766f664d from a common [ex17.geo.tar.gz](https://github.com/nschloe/meshio/files/2959646/ex17.geo.tar.gz) generated by pygmsh.  

It's a real example, from [scikit-fem/docs/examples/ex17.py](https://github.com/kinnala/scikit-fem/blob/6c1be376130f0152ead741b31dad7b212871f4d1/docs/examples/ex17.py), with 3-node triangular domain elements in two Physical Surfaces (subdomains) and 2-node line boundary elements in a Physical Line.

The two meshes were generated with
```shell
gmsh -2 -format msh2 -o ex17-2.2.msh ex17.geo
gmsh -2 -o ex17-4.1.msh ex17.geo
```

The second, being MSH4.1 #330, cannot be read by current master, pending merging of #331; it is read successfully (producing an identical `meshio.Mesh`) on branch gdmcbain:msh4-1-330.

### CODE REVIEW

**Comment by gdmcbain** [comment]
I think that the corresponding tests have to go in a different pull request?  Because they're destined for a different branch.

**Comment by nschloe** [comment]
Perhaps we can also add a README.md to the folder saying how to generate the files or where they're coming from.

**Comment by gdmcbain** [comment]
Done.

To make that a bit cleaner, I've simplified the GEO file by hand, removing the pygmsh artefacts.  I also increased the characteristic length so that the files are an order of magnitude smaller; I figure a hundred elements is good as a thousand for the present purpose.

I'm not exactly sure how reproducible MSH files are from GEO (with respect to a measure like `mesh.points.sum()`).   I know that a lot of mesh generation techniques include random steps and even though Gmsh has done something to improve reproducibility on a single host by seeding the random number generator, I don't know how that goes if the operating system has a different random number generator?   I could imagine all kinds of things like that that could go wrong, but the idea of the suite is to have static mesh files; anyway, the README.md, insulated.geo, and Makefile show how to make meshes like those provided.

**Comment by nschloe** [comment]
> I figure a hundred elements is good as a thousand for the present purpose.

:+1: 


> I'm not exactly sure how reproducible MSH files are from GEO (with respect to a measure like mesh.points.sum()).

Never mind that for now. The geo files are more than enough.

**Pull request merged**
