### PR TITLE
Use default ASCII float format '.16e'

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dalcinl** [comment]
@nschloe Please note I changed argument order (`float_fmt` and `binary`) in gmsh 4.1 private functions. I did it for consistency with the other gmsh formats. If you do not like it, let me know, but please let's use the same for all gmsh format implementations.

**Comment by dalcinl** [comment]
Oh, I missed your other message. Do you want me to edit the commit messages?

**Comment by nschloe** [comment]
Just put it in the code somwhere.

**Comment by dalcinl** [comment]
@nschloe Ready for merge.

**Comment by nschloe** [comment]
Thanks!

**Pull request merged**
