### PR TITLE
Change names for higher order elements

### PR DESCRIPTION
**Pull request by chrisrichardson**
Names are abbreviated in XDMF format.

### CODE REVIEW

**Comment by nschloe** [comment]
In http://www.xdmf.org/index.php/XDMF_Model_and_Format#XML_Element_.28Xdmf_ClassName.29_and_Default_XML_Attributes, I see the keywords as they are implemented now. As usual, there's appears to be no consistency. I'd be fine with _adding_ the abbreviated keywords. The reversed list `meshio_to_xdmf_type` should probably be made explicit.

**Comment by nschloe** [comment]
Hang on, I have a better idea.

**Comment by chrisrichardson** [comment]
You're probably right - maybe it accepts both `Tri_6` and `Triangle_6`. We can check the VTK source code...

**Comment by nschloe** [comment]
I've coughed up something in #165, will merge and release if it passes.

**Comment by chrisrichardson** [comment]
So, this page: http://www.xdmf.org/index.php/XDMF_Model_and_Format has `Tri_6` and `Tet_10` etc., and it seems to work in paraview... but the Xdmf source has `Triangle_6` etc. I can ask Dave Demarle about it.

**Comment by nschloe** [comment]
Never mind asking, #165 allows for both variants so we should be good.

**Comment by nschloe** [comment]
Alright, check out 1.10.3.

**Pull request closed without merging**
