### PR TITLE
write cell_sets more carefully

### PR DESCRIPTION
**Pull request by gdmcbain**
Each value in cell_sets now has cell-indices carefully written to the correctly indexed item in the list corresponding to the cell-blocks.

### CODE REVIEW

**Comment by nschloe** [comment]
I'm getting
```
ImportError: No module named 'numpy'
```
on another PR as well. This is only for Python 3.5. No idea what's wrong here.

**Comment by gdmcbain** [comment]
Hmm, no, I have no idea either.  Sorry.

Here I tried:
```shell
conda deactivate
conda create -n meshio-py35 python=3.5
conda activate meshio-py35
conda install pip
pip install -e ~/src/meshio
```
which brought in numpy-1.18.1
```shell
pip install pytest-xdist
pytest -n auto ~/src/meshio/test
```
That failed 32 because of h5py.
```shell
pip install h5py
pytest -n auto ~/src/meshio/test
```
which passed 436 and skipped 62.

**Comment by gdmcbain** [comment]
Running the same script as in #536 in this Python 3.5.6 conda env gives:
```
Electrically Grounded : [2, 3]
Mechanically Clamped : [8, 9]
Mechanically Free : [0, 1, 4, 5, 6, 7]
Electrically Free : [7, 9]
Piezoelectricity : [8, 9, 10, 11, 12, 13, 14, 15]
Structural Mechanics : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Electrically Clamped : [4, 5]
```
which is the same as the result obtained there in Python 3.7.3 except for the `dict` not being ordered (which is acceptable and expected).

**Comment by MEMAndersen** [comment]
How would I go about testing this new package. Can I simply download gdmcbains branch and import it like:
`import meshio.meshio`
 or do I need to install it in a virtual environment? I am interested in testing it for a 3d solid mesh like this one:

https://pastebin.com/XJH3q12K

This one has PhysicalVolumes overlapping, which the other example does not.

**Comment by nschloe** [comment]
Okay, I've disabled the 3.5 test for now.

**Comment by gdmcbain** [comment]
> How would I go about testing this new package. Can I simply download gdmcbains branch and import it like:
```python
import meshio.meshio
```
> or do I need to install it in a virtual environment?

This is no longer necessary since this PR has been merged into master, but for future reference see [‘Git branching—remote branches’](https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches).  

Something like:
```shell
git remote add gdmcbain git@github.com:gdmcbain/meshio
git fetch gdmcbain/536-msh41-multiple-tags  # Except that I'm about to delete it.
git checkout --track gdmcbain/536-msh-multiple-tags
```

Virtual environments aren't related to git so are irrelevant here; I mentioned the conda env above as a way of switching between versions of Python.

**Comment by gdmcbain** [comment]
> I am interested in testing it for a 3d solid mesh like this one:

    https://pastebin.com/XJH3q12K

> This one has PhysicalVolumes overlapping, which the other example does not.

Thank you for the test case.  I think it looks O. K. here, using master after the merger of this PR; I find that `'clay'` consists of the first 75 tetra of `'domain'` and `'soil'` of the remaining 77.

**Comment by MEMAndersen** [comment]
I have also run some tests now and find that everything works. I am a huge fan of the new cell_sets methodology! Thanks a bunch

**Pull request merged**
