### PR TITLE
WIP: minimally harvest MEDIT mesh ref

### PR DESCRIPTION
**Pull request by gdmcbain**
This fulfils #296 with minimal changes.

TODO:

- Testing.

- What to call the elemental tags; i.e. not "gmsh:physical".

- Try out for real in nschloe/pygmsh#212

- Read each type of element as a block rather than linewise.

### CODE REVIEW

**Comment by gdmcbain** [comment]
On testing.  In #292, @nschloe [asked](https://github.com/nschloe/meshio/pull/292#issuecomment-417213007):
> So point data and cell data tests remain disabled for now because there's no writer yet, right?

On looking at `helpers.add_point_data` and `add_cell_data`, I realize that they're inappropriate for MEDIT mesh.  This format does not hold point or cell data.  It does have an `int` tag for each point and cell, but I'm pretty sure that it would be an unidiomatic abuse to put floating-point data in there.

Instead, for MEDIT, according to Frey (2001, §7.2.4 ‘The `bb` format’), it is stored in a separate auxiliary file:

> This ASCII file contains scalar/tensor values associated with mesh entities. This file (`xxx.bb`) has
the following structure :
> _dim, nbmet, nbval, type_
> <i>v<sup>i</sup>, i</i> ∈ [1¸…, _nbmet, nbval_]
 
Reading and writing those does sound like a worthwhile future project but it does look quite distinct from the handling of regions #290, even though since #175 regions have been implemented in meshio sort of as if they were the same kind of thing as node or cell data.

I think it would be a mistake to read a MEDIT `mesh` file and extract the tags and then write them back out in a MEDIT `bb` file.

**Comment by gdmcbain** [comment]
Dobrzynski (§A.0.0.1.2 ‘`SOL` file‘)[’ https://www.math.u-bordeaux.fr/~dobrzyns/logiciels/RT-422/node60.html] describes a different file format to the `bb`file.

**Comment by nschloe** [comment]
> I think it would be a mistake to read a MEDIT mesh file and extract the tags and then write them back out in a MEDIT bb file.

Okay, sure. What we do in MSH2 for geometrical and physical tags is that the (`int`!) data gets an appropriate name that, when detected by the writer, will treat it differently than the other node/element data. We could do the same here.

**Comment by gdmcbain** [comment]
I think that this is ready now, reading nodal and elemental _ref_, storing them as `point_data["medit:ref"]` and `cell_data[type]["medit:ref"]`, and writing them.  This thus fixes #296 and #279.

Of the items in the TODO at the top:

- This passes the original `test_medit`.

  - With `hex_mesh` added, though that was orthogonal to #296.

  - It doesn't attempt to add `add_point_data` or `add_cell_data` from `helpers` as floating-point data is handled quite differently to tags in MEDIT.  A new issue should be raised for this if required.

 - It doesn't attempt to test the new functionality as there aren't any tests for tagged subsets of elements yet.  Should a new test be added for this, like `test_gmsh.gmsh_periodic`?  (I note that the same feature for Gmsh, "gmsh:physical", isn't tested either.)

- Use of this for nschloe/pygmsh#212 to follow, not affecting this package.

- Reading each block of elements as a block should be a separate issue, as in #291 


Also, it doesn't attempt to preserve physical tags during conversion between Gmsh MSH2 and MEDIT mesh in either direction.  I think that this would be reasonably straightforward, but it depends on the mesh-independent representation of tagged subsets of elements #290.

**Comment by nschloe** [comment]
Looks good to me.

**Pull request merged**
